import {parkVisitorPose} from './world-rules.js?v=0.10.0';
import {ICECREAM,iceCreamPrice} from './icecream.js?v=0.10.0';
import {installIceCreamArt} from './icecream-art.js?v=0.10.0';
import {batchStatic} from './static-batches.js?v=0.10.0';
import * as THREE from '../vendor/three.module.js?v=0.10.0';
import {BUSINESSES,businessById,businessRate,businessPlacementError} from './business-content.js?v=0.10.0';
import {businessPiece} from './business-art.js?v=0.10.0';
export function installBusinessUI({model,save,yard,pause,toast}){
 const dialog=document.createElement('dialog');dialog.id='town-book';dialog.innerHTML=`<header><div><h2>JUNK TO MAIN STREET</h2><p data-wallet></p></div><button data-exit aria-label="Return to junkyard">×</button></header><label>YOUR NEXT BIG THING <select aria-label="Business to visit">${BUSINESSES.map(d=>`<option value="${d.id}">${d.kind}</option>`).join('')}</select></label><p data-goal></p><div class="town-layout"><div class="town-world"><canvas aria-label="Business plot: tap or drag to position the selected building"></canvas><p data-world-status aria-live="polite"></p><button data-back hidden>BACK TO BUILDING</button></div><section data-catalog></section></div><section data-placement hidden><strong></strong><p>Tap or drag the ground. Keep the central visitor path clear.</p><div><button data-rotate="-1" aria-label="Rotate building left">↶ 45°</button><button data-rotate="1" aria-label="Rotate building right">↷ 45°</button><button data-confirm>PLACE</button><button data-cancel>CANCEL</button></div></section>`;document.body.append(dialog);
 const canvas=dialog.querySelector('canvas'),catalog=dialog.querySelector('[data-catalog]'),controls=dialog.querySelector('[data-placement]'),select=dialog.querySelector('select');let selected='icecream',renderer=null,ghost=null,editing=null,position=null,drag=false,watching=false,frameId=0,last=0,clock=0,lastUI=0;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#F6E3C4');const camera=new THREE.PerspectiveCamera(42,1,.1,100);scene.add(new THREE.HemisphereLight(0xfff5e4,0xbb9c77,2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(-8,15,8);sun.castShadow=true;sun.shadow.mapSize.set(512,512);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.1,far:80});sun.shadow.normalBias=.035;scene.add(sun);
 const lot=new THREE.Group(),buildings=new THREE.Group(),visitors=new THREE.Group();scene.add(lot,buildings,visitors);
 yard.box(80,.2,80,'#B9E77B',lot,0,-.5,0);yard.box(23,.08,2,'#8D99A6',lot,0,-.15,10);for(const x of [-12,-9,9,12]){yard.box(.35,1.8,.35,'#C48F52',lot,x,.4,-10);yard.cylinder(1.2,2.2,'#7CD35B',lot,x,1.8,-10);}
 yard.box(18,.3,16,'#D9A86A',lot,0,-.2,0);yard.box(2.5,.08,15,'#FFFFFF',lot,0,.02,0);
 for(const x of [-8.5,8.5])yard.box(.15,.35,15,'#FFFFFF',lot,x,.2,0);for(const z of [-7.5,7.5])yard.box(17,.35,.15,'#FFFFFF',lot,0,.2,z);
 for(let i=0;i<6;i++){const g=new THREE.Group();yard.box(.4,.65,.3,['#FF4D5A','#3A86FF','#FFD23F'][i%3],g,0,.6,0);yard.box(.3,.3,.3,'#D9A86A',g,0,1.08,0);visitors.add(g);}
 batchStatic(lot,[yard.boxGeometry,yard.cylinderGeometry]);
 const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
 const iceArt=installIceCreamArt(yard,scene);
 const state=()=>save.businesses[selected];
 function resize(){if(!renderer||!dialog.open)return;const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.position.set(12,23,24).multiplyScalar(Math.max(1,.95/camera.aspect));camera.lookAt(0,0,0);if(watching&&selected==='icecream'&&state().placements.counter){const q=state().placements.counter;camera.position.set(6,10,12).multiplyScalar(Math.max(1,.7/camera.aspect));camera.position.x+=q.x;camera.position.z+=q.z+1.5;camera.lookAt(q.x,0,q.z+1.5);}camera.updateProjectionMatrix();}
 function syncArt(){buildings.traverse(g=>{if(g.isInstancedMesh)g.dispose();});buildings.clear();const d=businessById(selected),s=state();for(const p of d.pieces){const preview=s.owned?null:({x:p.id===d.pieces[1].id?4:-4,z:p.id===d.pieces[2].id?4:-3,rotation:0});const q=s.placements[p.id]||(p.required?preview:null);if(!q||p.id===editing?.id)continue;const g=businessPiece(yard,p.shape,s.owned?d.color:'#8D99A6');g.position.set(q.x,0,q.z);g.rotation.y=q.rotation;batchStatic(g,[yard.boxGeometry,yard.cylinderGeometry]);buildings.add(g);}visitors.visible=s.open&&selected!=='icecream';}
 function supplyPanel(){return '<section class="ice-supplies"><h3>STAFF & SUPPLIES</h3><p data-ice-status></p><button data-hire>HIRE SCOOPS · $250</button><div><button data-stock="20">20 SERVINGS · $60</button><button data-stock="100">100 SERVINGS · $300</button></div><p data-ice-price></p><p>One-time hire. Scoops serves automatically while you play. Each sale uses one serving. Empty shelves pause service; waiting customers are patient.</p></section>';}
 function wallet(){dialog.querySelector('[data-wallet]').textContent=`$${save.cash.toLocaleString()} · ${save.buildParts} BUILDING PARTS`;const s=state(),d=businessById(selected);if(!editing)dialog.querySelector('[data-world-status]').textContent=s.open&&selected==='icecream'?`OPEN · ${!s.staff?'HIRE A WORKER':!s.stock?'RESTOCK TO SERVE':s.queue?'SERVING CUSTOMERS':'WAITING FOR CUSTOMERS'} · ${s.queue} in line · ${s.stock} servings`:s.open?`OPEN · $${businessRate(d,s)}/minute · earned $${s.earned.toLocaleString()} · next payment in ${Math.ceil(60-s.elapsed)}s`:s.owned?'YOUR PLOT · build and place the three essentials':'FUTURE BUSINESS PREVIEW · buy this plot to build your own layout';}
 function refreshControls(){const s=state(),d=businessById(selected),status=catalog.querySelector('[data-ice-status]');if(status){status.textContent=(s.staff?'SCOOPS HIRED':'NO WORKER YET')+' · '+s.stock+'/200 servings · '+s.served+' customers served';catalog.querySelector('[data-hire]').hidden=s.staff;catalog.querySelector('[data-hire]').disabled=save.cash<ICECREAM.hireCost;catalog.querySelector('[data-ice-price]').textContent='$'+iceCreamPrice(d,s)+' per sale · $3 supply cost · $'+s.earned.toLocaleString()+' total sales';catalog.querySelectorAll('[data-stock]').forEach(b=>{const n=Number(b.dataset.stock);b.disabled=s.stock+n>200||save.cash<n*3;});}catalog.querySelectorAll('[data-piece]').forEach(b=>{const p=d.pieces.find(p=>p.id===b.dataset.piece);b.disabled=!s.built.includes(p.id)&&(save.cash<p.cash||save.buildParts<p.parts);});const land=catalog.querySelector('[data-land]');if(land)land.disabled=!model.business.unlocked(selected)||save.cash<d.land;}
 function render(){const d=businessById(selected),s=state(),index=BUSINESSES.indexOf(d);dialog.querySelector('[data-goal]').textContent=d.name+' — '+d.description;wallet();
 if(!s.owned){catalog.innerHTML=`<h3>${d.kind}</h3><p>Land: $${d.land.toLocaleString()}</p><p>${selected==='icecream'?'Sell ice cream for $8 per serving. Hire Scoops for $250 and buy supplies for $3 per serving. Optional additions add $1 to each sale.':'Opening income: $'+d.rate+'/minute. Each placed optional addition adds 15% of base income.'}</p><p>${model.business.unlocked(selected)?'Buy the plot, then build its three essentials using cash and salvaged parts.':'FIRST: open '+BUSINESSES[index-1].name+'.'}</p><button data-land ${!model.business.unlocked(selected)||save.cash<d.land?'disabled':''}>BUY LAND · $${d.land.toLocaleString()}</button><p>Salvage vehicles at the junkyard for building parts. Businesses earn while you play or visit town, with no collection chores.</p>`;}
 else {const ready=d.pieces.filter(p=>p.required).every(p=>s.placements[p.id]);catalog.innerHTML=`<h3>${s.open?'OPEN FOR BUSINESS':'BUILD YOUR BUSINESS'}</h3><p>${d.pieces.filter(p=>p.required&&s.placements[p.id]).length}/3 essentials placed · ${save.buildParts} parts available</p>${s.open?`<p>Next ambition: ${BUSINESSES[index+1]?.name??'Finish all five businesses and their optional additions!'}</p>`:`<button data-open ${ready?'':'disabled'}>OPEN ${d.kind}</button>`}${s.open?'<button data-watch>WATCH BUSINESS</button>':''}${selected==='icecream'?supplyPanel():''}<div class="town-pieces">${d.pieces.map(p=>`<article><h4>${p.name}</h4><p>${p.required?'OPENING ESSENTIAL':selected==='icecream'?'+$1/SALE WHEN PLACED':'+$'+Math.round(d.rate*.15)+'/MIN WHEN PLACED'} · ${s.placements[p.id]?'Placed':s.built.includes(p.id)?'Built, ready to place':'$'+p.cash.toLocaleString()+' + '+p.parts+' parts'}</p><button data-piece="${p.id}" ${!s.built.includes(p.id)&&(save.cash<p.cash||save.buildParts<p.parts)?'disabled':''}>${s.built.includes(p.id)?'MOVE / PLACE':'BUILD & PLACE'}</button></article>`).join('')}</div><p>Cancel keeps built pieces in storage. Move them free. Open businesses keep earning when you return to the yard.</p>`;}
 refreshControls();syncArt();resize();}
 function placementStatus(){const error=businessPlacementError(state(),editing.id,position);dialog.querySelector('[data-world-status]').textContent=error||'Ready to place!';dialog.querySelector('[data-confirm]').disabled=!!error;ghost.position.set(position.x,0,position.z);ghost.rotation.y=position.rotation;}
 function startPlacement(p){wallet();editing=p;position={...(state().placements[p.id]||{x:-4,z:0,rotation:0})};ghost=businessPiece(yard,p.shape,businessById(selected).color);scene.add(ghost);catalog.hidden=true;controls.hidden=false;select.disabled=true;controls.querySelector('strong').textContent='PLACE '+p.name.toUpperCase();dialog.classList.add('town-placing');syncArt();resize();placementStatus();dialog.scrollTop=0;dialog.querySelector('[data-confirm]').focus();}
 function endPlacement(){scene.remove(ghost);ghost=null;editing=null;drag=false;catalog.hidden=false;controls.hidden=true;select.disabled=false;dialog.classList.remove('town-placing');render();}
 function pointer(e){if(!ghost)return;const r=canvas.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);if(ray.ray.intersectPlane(plane,hit)){position.x=Math.round(hit.x*2)/2;position.z=Math.round(hit.z*2)/2;placementStatus();}}
 canvas.addEventListener('pointerdown',e=>{if(!ghost)return;drag=true;canvas.setPointerCapture(e.pointerId);pointer(e);});canvas.addEventListener('pointermove',e=>{if(drag)pointer(e);});for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,()=>drag=false);
 function watch(value){watching=value;dialog.classList.toggle('town-watching',value);catalog.hidden=value;dialog.querySelector('[data-back]').hidden=!value;dialog.scrollTop=0;resize();}
 function close(){watch(false);if(editing)endPlacement();cancelAnimationFrame(frameId);model.persist();dialog.close();pause(document.hidden);document.getElementById('game').focus();}
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(editing)endPlacement();else if(watching)watch(false);else close();});select.onchange=()=>{selected=select.value;render();};
 dialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-watch'))return watch(true);if(b.hasAttribute('data-back'))return watch(false);if(b.hasAttribute('data-exit'))return close();if(b.hasAttribute('data-hire')){if(model.business.hire())render();}if(b.dataset.stock){if(model.business.restock(Number(b.dataset.stock)))render();}if(b.hasAttribute('data-land')){if(model.business.buyLand(selected))render();}if(b.hasAttribute('data-open')){if(model.business.open(selected)){render();toast(businessById(selected).name+' is OPEN!');}}if(b.dataset.piece){const p=businessById(selected).pieces.find(p=>p.id===b.dataset.piece);if(state().built.includes(p.id)||model.business.build(selected,p.id))startPlacement(p);}if(b.dataset.rotate&&editing){position.rotation=(position.rotation+Number(b.dataset.rotate)*Math.PI/4+Math.PI*2)%(Math.PI*2);placementStatus();}if(b.hasAttribute('data-confirm')&&editing&&model.business.place(selected,editing.id,position))endPlacement();if(b.hasAttribute('data-cancel')&&editing)endPlacement();};
 function frame(now){if(!dialog.open)return;frameId=requestAnimationFrame(frame);const dt=document.hidden?0:Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;clock+=dt;model.business.tick(dt);if(now-lastUI>500){wallet();refreshControls();lastUI=now;}iceArt.update(save.businesses.icecream,dt,selected==='icecream'&&state().open&&editing?.id!=='counter',save.settings.reduced);if(state().open){visitors.children.forEach((g,i)=>{const q=parkVisitorPose(clock,i);g.position.set(q.x,0,q.z);g.rotation.y=q.heading;});if(!save.settings.reduced)buildings.traverse(g=>{if(g.userData.spin)g.rotation.y+=dt*.8;if(g.userData.sway)g.rotation.z=Math.sin(clock*2)*.05;});}renderer.render(scene,camera);}
 addEventListener('resize',resize);
 return{isOpen:()=>dialog.open,open(id){if(id&&businessById(id)){selected=id;select.value=id;}if(['pressing','impact'].includes(model.state))return;pause(true);dialog.showModal();if(!renderer){renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,save.settings.reduced?1:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;}render();last=performance.now();frameId=requestAnimationFrame(frame);}};
}
