const piece=(id,name,shape,cash,parts,required=true)=>({id,name,shape,cash,parts,required});
export const BUSINESSES=[
 {id:'icecream',name:'Scoops & Scrap',kind:'ICE CREAM SHOP',color:'#FF91CF',land:450,rate:35,description:'Turn a rescued ice cream van into your first neighborhood business.',pieces:[piece('counter','Ice cream van','van',300,2),piece('entrance','Welcome arch','arch',100,1),piece('seats','Picnic tables','tables',120,1),piece('flavors','Rainbow flavor stand','cone',350,2,false),piece('garden','Candy garden','garden',180,1,false),piece('sign','Giant ice cream sign','cone',240,1,false)]},
 {id:'dino',name:'Rustassic Park',kind:'DINO PARK',color:'#7CD35B',land:2500,rate:80,description:'Build towering scrap dinosaurs and welcome your first explorers.',pieces:[piece('dinosaur','Scrap T-rex','dino',1800,5),piece('entrance','Explorer gate','arch',600,2),piece('trail','Explorer boardwalk','trail',500,2),piece('hatchery','Baby dinosaur hatchery','dino',1100,3,false),piece('garden','Prehistoric garden','garden',700,2,false),piece('seats','Explorer picnic spot','tables',500,1,false)]},
 {id:'zoo',name:'Bolt Buddies Zoo',kind:'ROBOT ZOO',color:'#69E6FF',land:5000,rate:160,description:'Give rescued metal a second life as friendly mechanical animals.',pieces:[piece('animals','Robot animal exhibit','animals',2600,7),piece('entrance','Zoo entrance','arch',900,3),piece('trail','Safari boardwalk','trail',800,2),piece('frog','Giant spring frog','frog',1200,3,false),piece('cat','Mechanical cat habitat','cat',1200,3,false),piece('garden','Habitat garden','garden',900,2,false)]},
 {id:'rides',name:'Scrapland',kind:'AMUSEMENT PARK',color:'#FFD23F',land:9000,rate:260,description:'Build a working carousel from salvaged machines and goofy scrap rides.',pieces:[piece('ride','Junk carousel','carousel',4200,10),piece('entrance','Ticket gate','arch',1500,3),piece('seats','Rest area','tables',1000,3),piece('rocket','Rocket ride','rocket',2300,5,false),piece('snacks','Snack kiosk','kiosk',1600,3,false),piece('garden','Festival garden','garden',1200,2,false)]},
 {id:'cinema',name:'Bumper Picture Palace',kind:'DRIVE-IN CINEMA',color:'#B58CFF',land:14000,rate:400,description:'Restore old cars as seats and open a colorful outdoor picture palace.',pieces:[piece('screen','Big movie screen','screen',6000,12),piece('entrance','Box office','kiosk',2200,4),piece('seats','Restored car seats','cars',1800,4),piece('snacks','Popcorn stand','kiosk',2200,4,false),piece('sign','Rocket marquee','rocket',2400,5,false),piece('garden','Starlight garden','garden',1800,3,false)]}
];
export const businessById=id=>BUSINESSES.find(b=>b.id===id);
export const emptyBusiness=()=>({owned:false,open:false,built:[],placements:{},elapsed:0,earned:0,staff:false,stock:0,served:0,queue:0,arrival:0,service:0});
export function businessRate(def,state){return def.rate+state.built.filter(id=>def.pieces.find(p=>p.id===id&&!p.required)&&state.placements[id]).length*Math.round(def.rate*.15);}
export function businessPlacementError(state,id,p){
 if(!p||![p.x,p.z,p.rotation].every(Number.isFinite)||Math.abs(p.x)>6.5||Math.abs(p.z)>5.5)return 'Place inside the marked plot.';
 if(Math.abs(p.x)<3.5)return 'Keep the center visitor path clear.';
 for(const [other,q] of Object.entries(state.placements))if(other!==id&&Math.hypot(p.x-q.x,p.z-q.z)<3.6)return 'Leave room between buildings.';
 return '';
}
export function normalizeBusinesses(raw){const result={};for(const def of BUSINESSES){const r=raw?.[def.id],s=emptyBusiness();if(!r){result[def.id]=s;continue;}s.owned=r.owned===true;s.built=s.owned&&Array.isArray(r.built)?[...new Set(r.built.filter(id=>def.pieces.some(p=>p.id===id)))]:[];for(const id of s.built){const p=r.placements?.[id];if(p&&!businessPlacementError(s,id,p))s.placements[id]={x:p.x,z:p.z,rotation:p.rotation%(Math.PI*2)};}s.open=s.owned&&r.open===true&&def.pieces.filter(p=>p.required).every(p=>s.placements[p.id]);s.elapsed=Number.isFinite(r.elapsed)&&r.elapsed>=0&&r.elapsed<60?r.elapsed:0;s.earned=Number.isSafeInteger(r.earned)&&r.earned>=0?r.earned:0;if(def.id==='icecream'){s.staff=s.owned&&r.staff===true;for(const [key,max] of [['stock',200],['served',Number.MAX_SAFE_INTEGER],['queue',5]]){const v=r[key]??0;if(!Number.isSafeInteger(v)||v<0||v>max)throw new Error('Invalid ice cream '+key);s[key]=s.owned?v:0;}for(const [key,max] of [['arrival',3],['service',4]]){const v=r[key]??0;if(!Number.isFinite(v)||v<0||v>=max)throw new Error('Invalid ice cream '+key);s[key]=v;}if(!s.open){s.queue=0;s.arrival=s.service=0;}if(!s.queue||!s.stock||!s.staff)s.service=0;}
 result[def.id]=s;}return result;}
