import {installBusinessUI} from './business-ui.js?v=0.9.0';
import {installDecorPlacement} from './decor-placement.js?v=0.9.0';
import {decorLayout} from './decor-layout.js?v=0.9.0';
import {decorationPreviews} from './fun-art.js?v=0.9.0';
import {SPECIALS,DECORATIONS,DISPLAY_SPOTS,CRANE} from './fun-content.js?v=0.9.0';
export function installFunUI({model,save,near,pause,toast,yard}){
 const open=document.createElement('button');open.id='fun-open';open.textContent='FUN YARD';document.body.append(open);
 const salvage=document.createElement('button');salvage.id='salvage-part';document.body.append(salvage);salvage.onclick=()=>model.fun.salvage();
 const book=document.createElement('dialog');book.id='fun-book';book.innerHTML='<header><h2>MAKE IT YOUR YARD</h2><button aria-label="Close fun yard" data-close>×</button></header><nav><button data-town>BUSINESSES</button><button data-tab="decor">DECORATE</button><button data-tab="deliveries">SILLY DELIVERIES</button><button data-tab="crane">MAGNET CRANE</button></nav><p id="fun-wallet"></p><section id="fun-content"></section>';document.body.append(book);
 const town=installBusinessUI({model,save,yard,pause,toast});
 const previews={};let tab='decor',theme='Candy';const content=book.querySelector('#fun-content');
 const placement=installDecorPlacement({yard,model,save,pause,toast,onDone:()=>document.getElementById('game').focus()});
 const close=()=>{book.close();pause(document.hidden);document.getElementById('game').focus();};book.querySelector('[data-close]').onclick=close;book.addEventListener('cancel',e=>{e.preventDefault();close();});
 function render(){book.querySelector('#fun-wallet').textContent=`YOUR CASH $${save.cash.toLocaleString()} · ${save.decorations.length}/${DECORATIONS.length} decorations owned`;
 if(tab==='decor'){const items=DECORATIONS.filter(d=>d.theme===theme);if(!previews[items[0].id])Object.assign(previews,decorationPreviews(yard,items));content.innerHTML='<p>Buy with earned cash, then move and rotate your decoration directly in the yard. Cancel keeps it in your collection. Moving owned decorations is free.</p><label>Collection <select id="decor-theme">'+['Candy','Sunshine','Cosmic'].map(t=>`<option ${theme===t?'selected':''}>${t}</option>`).join('')+'</select></label><div class="fun-grid">'+DECORATIONS.filter(d=>d.theme===theme).map(d=>`<article><img class="decor-preview" src="${previews[d.id]}" alt="${d.name} sculpture preview" width="128" height="128"><h3>${d.name}</h3><p>${decorLayout(save)[d.id]?'Displayed · move it for free':save.decorations.includes(d.id)?'Owned · free to place':'Permanent yard decoration'}</p><button data-decor="${d.id}" ${!save.decorations.includes(d.id)&&save.cash<d.cost?'disabled':''}>${save.decorations.includes(d.id)?'MOVE / PLACE':'BUY · $'+d.cost.toLocaleString()}</button></article>`).join('')+'</div>';}
 if(tab==='deliveries')content.innerHTML=`<p>A silly wreck arrives every third delivery, starting with wreck #3. All 24 themes rotate without random duplicates. They match equipment you can already use. Crush them for a souvenir stamp!</p><div class="fun-grid">${SPECIALS.map(d=>`<article><h3>${d.name}</h3><p>${save.specialDiscoveries.includes(d.id)?'STAMP COLLECTED · '+d.line:'Waiting to be discovered'}</p></article>`).join('')}</div>`;
 if(tab==='crane')content.innerHTML=`<h3>BIG MAGNET. BIG SCOOP.</h3><p>Move up to three scrap loads from the crusher to the baler. Walk beside the baler’s east side to operate it. Scoop, watch the swing, then return here to drop.</p><p>${save.craneCargo} loads on magnet · ${save.balerFeed}/3 in baler · ${save.scrapLoads} loose scrap</p>${!save.craneOwned?`<button data-crane="buy" ${!save.balerOwned||save.cash<CRANE.cost?'disabled':''}>${!save.balerOwned?'BUILD THE BALER FIRST':'BUILD CRANE · $'+CRANE.cost}</button>`:`<p>${!near(CRANE)?'Drive to the east side of the baler.':save.craneTimer?'Crane moving…':save.balerRemaining?'Baler busy. Magnet keeps its cargo safe.':'Ready for your next move.'}</p><button data-crane="scoop" ${!near(CRANE)||save.craneCargo||save.craneTimer||!save.scrapLoads||model.state!=='waiting'?'disabled':''}>SCOOP UP TO 3 LOADS</button><button data-crane="drop" ${!near(CRANE)||!save.craneCargo||save.craneTimer||save.balerRemaining||model.state!=='waiting'?'disabled':''}>SWING & DROP INTO BALER</button>`}`;
 }
 open.onclick=()=>{if(['pressing','impact'].includes(model.state))return;render();pause(true);book.showModal();};
 book.addEventListener('change',e=>{if(e.target.id==='decor-theme')theme=e.target.value;render();});
 book.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-town')){book.close();town.open();return;}if(b.dataset.tab){tab=b.dataset.tab;render();}if(b.dataset.decor){const id=b.dataset.decor;if(!save.decorations.includes(id)&&!model.fun.buy(id))return;book.close();placement.start(DECORATIONS.find(d=>d.id===id));}if(b.dataset.crane){const action=b.dataset.crane;const ok=action==='buy'?model.fun.buyCrane():near(CRANE)&&(action==='scoop'?model.fun.scoop():model.fun.drop());if(ok){close();toast(action==='buy'?'Magnet crane built! Drive to the east side of the baler.':action==='scoop'?'Magnet swinging! Reopen FUN YARD → MAGNET CRANE to drop.':'Delivering scrap to the baler!');}else render();}});
 return{isOpen:()=>book.open||placement.active()||town.isOpen(),update(){open.hidden=save.crushed<1;open.disabled=['pressing','impact'].includes(model.state);salvage.hidden=!['towing','ready'].includes(model.state)||save.salvagedDelivery===save.crushed||model.progressionDisabled;salvage.textContent='SALVAGE · +1 PART · +$'+Math.max(12,Math.round(model.vehicle.value*.3));}};
}
