import {valuation,yardValue,saleRequirements,canSell,countyStartingCash,sellYard,buySurplusPermit,claimCountyCollection} from './property.js?v=0.8.1';
import {COUNTY_VEHICLES} from './config.js?v=0.8.1';
export function installPropertyUI({save,model,store,pause,toast}){
  const button=document.createElement('button');button.id='property-open';button.textContent='Yard value';document.body.append(button);
  const dialog=document.createElement('dialog');dialog.className='property-dialog';dialog.setAttribute('aria-label','Property office');document.body.append(dialog);let review=false;
  const money=n=>'$'+n.toLocaleString();
  function render(){const county=save.yardId==='county';dialog.innerHTML=`<button class="icon-button property-close" data-action="close" aria-label="Close property office">×</button><span class="eyebrow">${county?'COUNTY PROPERTY OFFICE':'YOUR NEXT CHAPTER'}</span><h2>${county?'County Yard':review?'Review your yard sale':'A business worth building.'}</h2>`;
    if(county){dialog.innerHTML+=`<p>You sold Rustbucket for a valuation of ${money(save.soldYardValue)}. Your permanent legacy bonus adds <b>25% to every crush payout</b>.</p><p>County service vehicles and works trucks are now available. Build your handling and press power for heavier jobs.</p><button class="primary" data-action="permit" ${save.surplusPermit||save.cash<25000?'disabled':''}>${save.surplusPermit?'Surplus route open':'Open surplus route · $25,000'}</button><p>Unlocks fictional, unarmed utility carriers. Requires 4,500 kg lift and Power 8 to receive them.</p><button class="primary" data-action="collection" ${save.countyCollectionClaimed||!COUNTY_VEHICLES.every(v=>save.discoveries.includes(v.id))?'disabled':''}>${save.countyCollectionClaimed?'County collection bonus claimed':'Collect all 3 county wrecks · $7,500'}</button>`;
    }else if(review){dialog.innerHTML+=`<p><b>Move to County Yard with ${money(countyStartingCash(save))}.</b> Your new property includes the east lot, a Shop Forklift, Power 3, two speed upgrades, one value upgrade, a baler and Jo.</p><p><b>You keep:</b> decorations, silly stamps, discoveries, rare finds, collection bonuses, lifetime records, completed-contract count and settings. Every future crush gains a permanent 25% bonus.</p><p><b>You sell:</b> the old yard, its current cash and equipment. The magnet crane, south depot and remaining equipment upgrades will need rebuilding. Scrap, unfinished bales and the current job clear on the move.</p><p>A separate pre-sale save is kept locally. This move is optional and can happen once in this build.</p><button class="primary" data-action="sell" ${!canSell(save)||model.state!=='waiting'?'disabled':''}>Sell Rustbucket & move</button><button class="skip-job" data-action="back">Keep my yard for now</button>`;
    }else{dialog.innerHTML+=`<strong class="valuation-total">${money(yardValue(save))}</strong><div class="valuation-breakdown">${Object.entries(valuation(save)).map(([name,value])=>`<p><span>${name}</span><b>${money(value)}</b></p>`).join('')}</div><ul>${saleRequirements(save).map(r=>`<li>${r.done?'✓':'○'} ${r.label}</li>`).join('')}</ul><p>${model.state==='waiting'?'Sell when you are ready for a new property.':'Finish the current delivery before selling.'}</p><button class="primary" data-action="review" ${!canSell(save)||model.state!=='waiting'?'disabled':''}>Review offer for County Yard</button>`;}
  }
  const close=()=>{dialog.close();pause(document.hidden);document.getElementById('game').focus();};button.onclick=()=>{review=false;render();pause(true);dialog.showModal();dialog.querySelector('.property-close').focus({preventScroll:true});dialog.scrollTop=0;};dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
  dialog.onclick=e=>{const action=e.target.closest('button')?.dataset.action;if(action==='close')close();if(action==='review'){review=true;render();}if(action==='back'){review=false;render();}if(action==='sell'){if(!store.checkpoint(save)){toast(store.warning);return;}if(sellYard(model,state=>store.save(state))){close();toast('SOLD! Welcome to County Yard. Your legacy adds 25% to every crush.');}else toast('Sale could not complete. Your yard is unchanged.');}if(action==='permit'){if(buySurplusPermit(model))toast('Surplus route unlocked.');render();}if(action==='collection'){if(claimCountyCollection(model))toast('County collection complete! +$7,500');render();}};
  return{isOpen:()=>dialog.open,update(){button.hidden=!save.landOwned;button.textContent=save.yardId==='county'?'Property office':canSell(save)?'Offer ready!':'Yard value';}};
}
